### ISSUE TITLE
puppetserver::repository should handle the PC1 repo ?

### ISSUE THREAD

**Issue by olivierHa** [voxpupuli/puppet-puppetserver#18]
Hello, 

Actually, only the "main" repository is configured, so we can't install a puppetserver 2.x

Is this addition to the "puppetserver::repository"  class something we could include for debian ? 

``` puppet
  if versioncmp($::puppetversion, '4.0.0') >= 0 {
    $targetrepo = 'PC1'
  } else {
    $targetrepo = 'main'
  }
```

(same thing for products for rhel)

Or maybe you got another idea that isn't just pushed yet ?
I can do a PR, but I wanted to know if it is the "good way" :)

Regards

Olivier

**Comment by raphink** [comment]
Yes, that is a good option. Can you turn this into a PR please?

**Comment by kostecky** [comment]
I've done this in a way where it's user specifiable @ https://github.com/camptocamp/puppet-puppetserver/pull/20

However, some of the travis tests are failing and when I introspect them it doesn't appear to be from the changes I've made. Thanks.

**Comment by vinzent** [comment]
closing in favor of https://github.com/voxpupuli/puppet-puppetserver/issues/37
