### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by elconas** [voxpupuli/puppet-puppetserver#43]
It seems that the module is only compatible with puppet4 since https://github.com/voxpupuli/puppet-puppetserver/pull/42 has been merged. (As https://forge.puppet.com/puppetlabs/puppetserver_gem is puppet 4 only). So it would be time for a 3.0 release ? 

Also metadata dependencies have to be updated.

**Comment by vinzent** [comment]
Am 5. Februar 2017 17:03:42 MEZ schrieb "www.elconas.de" <notifications@github.com>:
>It seems that the module is only compatible with puppet4 since
>https://github.com/voxpupuli/puppet-puppetserver/pull/42 has been
>merged. (As https://forge.puppet.com/puppetlabs/puppetserver_gem is
>puppet 4 only). So it would be time for a 3.0 release ? 

Yes. Merging the open java args pr then we can do a release.

**Comment by elconas** [comment]
@vinzent When can we expect a Release ?

**Comment by stefanbethke** [comment]
Any chance we can see a release anytime soon?

**Comment by vinzent** [comment]
@stefanbethke @elconas OK ! i'm doing a release

**Comment by stefanbethke** [comment]
Thank you!

**Comment by vinzent** [comment]
@elconas @stefanbethke I'll need somebody to review https://github.com/voxpupuli/puppet-puppetserver/pull/50
