### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by vinzent** [voxpupuli/puppet-puppetserver#45]
Release last 2.2.0 in puppet3 branch according https://voxpupuli.org/blog/2017/01/11/migrating-to-puppet4/.

 needs to be based upon the commit before the puppetserver_gem change which does not support Puppet 3.8.

**Comment by elconas** [comment]
regarding puppetserver_gem: you can pull in https://github.com/voxpupuli/puppet-puppetserver/pull/29 .. this fixes the issue also.

**Comment by rnelson0** [comment]
Where are we at on this, can we do a release yet? camptocamp/puppetserver grated to us but the latest forge version is still from camptocamp and it's confusing users. Let me know what I can do to help.

**Comment by vinzent** [comment]
superseded by #50
