### ISSUE TITLE
puppetserver_gem provider requires PATH to include path to puppetserver binary

### ISSUE THREAD

**Issue by davealden** [voxpupuli/puppet-puppetserver#47]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any?
- Ruby: any?
- Distribution: any?
- Module version: 2.2.0

## How to reproduce (e.g Puppet code you use)
ensure('vault', {provider=>'puppetserver_gem'})

## What are you seeing
Error: /Stage[main]/Profile::Puppetmaster/Package[vault]: Provider puppetserver_gem is not functional on this host

## What behaviour did you expect instead
vault to be installed

## Any additional information you'd like to impart
Looking at lib/puppet/provider/package/puppetserver_gem.rb I see that it does a which('puppetserver'), hence the requirement that it be in the path.  But this is the only thing I've ever run in to that required puppetserver to be in the path when I run "puppet agent -t".  The puppetlabs/puppetserver_gem module doesn't do a which, it hard codes it to the path -- maybe this should do the same?

**Comment by maxadamo** [comment]
but, how about removing the puppetserver_gem support? 
There is an official puppetserver_gem module: [puppetserver_gem](https://forge.puppet.com/puppetlabs/puppetserver_gem)
but it's not possible to use that one along with this one: it keeps overwriting the ruby gem at each run.

**Comment by ZeroPointEnergy** [comment]
Looks like this provider is no longer in the module in the most recent version. This can probably be closed?
